// Generates src/schema/course.generated.ts from the embedded schema.
// Run with `npm run gen:types` whenever src/schema/schema.json changes.
// The node's content depends on its type through if/then, which no generator
// can follow, so `unreachableDefinitions` emits every content shape on its own
// and src/schema/types.ts ties them to the node types.
import { compile } from "json-schema-to-typescript";
import { readFileSync, writeFileSync } from "node:fs";

const schema = JSON.parse(readFileSync("src/schema/schema.json", "utf8"));
const ts = await compile(schema, "Course", {
  bannerComment:
    "/* Generated by scripts/gen-types.mjs from src/schema/schema.json. Do not edit by hand. */",
  additionalProperties: false,
  unreachableDefinitions: true,
  format: true,
});
writeFileSync("src/schema/course.generated.ts", ts);
console.log("wrote src/schema/course.generated.ts");
