# The interface strings, one row per key: (pt, en, es).
# scripts/build-locales.py writes src/i18n/locales/{pt,en,es}.json from this table.
S = {
# common / file / edit
"common.cancel": ("Cancelar", "Cancel", "Cancelar"),
"common.confirm": ("Confirmar", "Confirm", "Confirmar"),
"common.ok": ("OK", "OK", "Aceptar"),
"common.save": ("Salvar", "Save", "Guardar"),
"common.up": ("Subir", "Move up", "Subir"),
"common.down": ("Descer", "Move down", "Bajar"),
"common.working": ("Trabalhando…", "Working…", "Trabajando…"),
"file.new": ("Novo curso", "New course", "Nuevo curso"),
"file.open": ("Abrir…", "Open…", "Abrir…"),
"file.save": ("Salvar", "Save", "Guardar"),
"file.saveAs": ("Salvar como…", "Save as…", "Guardar como…"),
"file.recent": ("Arquivos recentes", "Recent files", "Archivos recientes"),
"file.untitled": ("Sem título", "Untitled", "Sin título"),
"file.untitledHint": ("{name} — ainda sem arquivo", "{name} — not saved to a file yet", "{name} — aún sin archivo"),
"file.newTitle": ("Novo curso", "New course", "Nuevo curso"),
"file.unsaved": ("Alterações não salvas", "Unsaved changes", "Cambios sin guardar"),
"file.openFailed": ("Não foi possível abrir", "Could not open", "No se pudo abrir"),
"file.saveFailed": ("Não foi possível salvar", "Could not save", "No se pudo guardar"),
"file.notJson": ("O arquivo não é um JSON válido.", "The file is not valid JSON.", "El archivo no es un JSON válido."),
"file.notCourse": ("O arquivo não tem 'nodes': não é um curso Edukors Graph.", "The file has no 'nodes': it is not an Edukors Graph course.", "El archivo no tiene 'nodes': no es un curso Edukors Graph."),
"edit.undo": ("Desfazer", "Undo", "Deshacer"),
"edit.redo": ("Refazer", "Redo", "Rehacer"),
"edit.cut": ("Recortar nós", "Cut nodes", "Cortar nodos"),
"edit.copy": ("Copiar nós", "Copy nodes", "Copiar nodos"),
"edit.paste": ("Colar nós", "Paste nodes", "Pegar nodos"),
"edit.delete": ("Excluir seleção", "Delete selection", "Eliminar selección"),
"edit.selectAll": ("Selecionar todos os nós", "Select all nodes", "Seleccionar todos los nodos"),
"unsaved.title": ("Alterações não salvas", "Unsaved changes", "Cambios sin guardar"),
"unsaved.message": ("“{name}” tem alterações que não foram salvas. O que fazer com elas?", "“{name}” has changes that were not saved. What should happen to them?", "“{name}” tiene cambios sin guardar. ¿Qué hacer con ellos?"),
"unsaved.discard": ("Descartar", "Discard", "Descartar"),
"tab.canvas": ("Mapa", "Map", "Mapa"),
"tab.json": ("JSON", "JSON", "JSON"),
"tab.preview": ("Preview", "Preview", "Vista previa"),
"tabs.label": ("Cursos abertos", "Open courses", "Cursos abiertos"),
"tabs.close": ("Fechar aba", "Close tab", "Cerrar pestaña"),
"ui.pt": ("Português", "Portuguese", "Portugués"),
"ui.en": ("Inglês", "English", "Inglés"),
"ui.es": ("Espanhol", "Spanish", "Español"),
"welcome.lead": ("Crie e edite cursos no padrão Edukors Graph: desenhe o grafo, escreva cada passo, valide, traduza e teste com a IA de verdade.", "Create and edit Edukors Graph courses: draw the graph, write each step, validate, translate and test with the real AI.", "Cree y edite cursos en el estándar Edukors Graph: dibuje el grafo, escriba cada paso, valide, traduzca y pruebe con la IA real."),
"welcome.samples": ("Exemplos", "Samples", "Ejemplos"),
# node types
"type.static-md": ("Texto", "Text", "Texto"),
"type.static-html": ("HTML", "HTML", "HTML"),
"type.dynamic-md": ("Texto com IA", "AI text", "Texto con IA"),
"type.dynamic-html": ("HTML com IA", "AI HTML", "HTML con IA"),
"type.quiz": ("Quiz", "Quiz", "Cuestionario"),
"type.form": ("Formulário", "Form", "Formulario"),
"type.bool": ("Sim/não", "Yes/no", "Sí/no"),
"type.choice": ("Escolha (IA)", "Choice (AI)", "Elección (IA)"),
"type.score": ("Nota (IA)", "Score (AI)", "Nota (IA)"),
"type.noul": ("Probabilidade (IA)", "Probability (AI)", "Probabilidad (IA)"),
"field.text-line": ("Linha de texto", "Text line", "Línea de texto"),
"field.text-area": ("Texto longo", "Text area", "Texto largo"),
"field.radio": ("Uma opção (radio)", "One option (radio)", "Una opción (radio)"),
"field.check": ("Várias opções (check)", "Several options (check)", "Varias opciones (check)"),
"field.select": ("Lista suspensa", "Drop-down", "Lista desplegable"),
# insert / canvas
"insert.button": ("Inserir nó", "Insert node", "Insertar nodo"),
"insert.content": ("Conteúdo", "Content", "Contenido"),
"insert.activities": ("Atividades", "Activities", "Actividades"),
"insert.judges": ("Julgamentos da IA", "AI judgements", "Juicios de la IA"),
"insert.hint": ("Clique para inserir ou arraste até o grafo.", "Click to insert, or drag onto the graph.", "Haga clic para insertar o arrastre al grafo."),
"canvas.label": ("Grafo do curso", "Course graph", "Grafo del curso"),
"canvas.start": ("Início do curso", "Course start", "Inicio del curso"),
"canvas.untitled": ("(sem título)", "(untitled)", "(sin título)"),
"canvas.fallback": ("caso contrário (fallback)", "otherwise (fallback)", "en otro caso (fallback)"),
"canvas.otherwise": ("senão", "else", "si no"),
"canvas.section": ("Seção {n}", "Section {n}", "Sección {n}"),
"canvas.layout": ("Organizar automaticamente", "Auto layout", "Organizar automáticamente"),
"canvas.fit": ("Enquadrar o grafo", "Fit the graph", "Encuadrar el grafo"),
"canvas.langHint": ("Idioma dos títulos no grafo", "Language of the titles on the graph", "Idioma de los títulos en el grafo"),
# inspector
"insp.panel": ("Inspetor", "Inspector", "Inspector"),
"insp.nothing": ("Nada selecionado.", "Nothing selected.", "Nada seleccionado."),
"insp.many": ("{n} nós selecionados. ⌫ exclui, ⌘D duplica, ⌘C copia.", "{n} nodes selected. ⌫ deletes, ⌘D duplicates, ⌘C copies.", "{n} nodos seleccionados. ⌫ borra, ⌘D duplica, ⌘C copia."),
"insp.add": ("Adicionar {what}", "Add {what}", "Añadir {what}"),
"insp.remove": ("Remover", "Remove", "Quitar"),
"insp.duplicate": ("Duplicar", "Duplicate", "Duplicar"),
"insp.delete": ("Excluir", "Delete", "Eliminar"),
"insp.rename": ("Renomear", "Rename", "Renombrar"),
"insp.idInvalid": ("Use o prefixo {prefix} seguido de um número livre.", "Use the prefix {prefix} followed by a free number.", "Use el prefijo {prefix} seguido de un número libre."),
"insp.section": ("Seção", "Section", "Sección"),
"insp.title": ("Título", "Title", "Título"),
"insp.isStart": ("Este é o nó de início do curso", "This is the course's start node", "Este es el nodo de inicio del curso"),
"insp.judgeNoStart": ("Um nó de julgamento não pode ser o início", "A judgement node cannot be the start", "Un nodo de juicio no puede ser el inicio"),
"insp.content": ("Conteúdo", "Content", "Contenido"),
"insp.prompt": ("Prompt", "Prompt", "Prompt"),
"insp.from": ("Escrito a partir do julgamento (from)", "Written from the judgement (from)", "Escrito a partir del juicio (from)"),
"insp.fromNone": ("— nenhum —", "— none —", "— ninguno —"),
"insp.fromHint": ("O nó recebe, depois do prompt, o state julgado e o julgamento completo. O prompt diz como escrever, nunca julga de novo.", "After the prompt the node receives the judged state and the full judgement. The prompt says how to write, never judges again.", "Tras el prompt el nodo recibe el state juzgado y el juicio completo. El prompt dice cómo escribir, nunca vuelve a juzgar."),
"insp.question": ("Pergunta", "Question", "Pregunta"),
"insp.questionN": ("Pergunta {n}", "Question {n}", "Pregunta {n}"),
"insp.yesLabel": ("Rótulo do sim", "Yes label", "Etiqueta del sí"),
"insp.noLabel": ("Rótulo do não", "No label", "Etiqueta del no"),
"insp.default": ("Resposta pré-selecionada", "Preselected answer", "Respuesta preseleccionada"),
"insp.defaultNone": ("— nenhuma (o estudante escolhe) —", "— none (the student chooses) —", "— ninguna (el estudiante elige) —"),
"insp.key": ("Chave", "Key", "Clave"),
"insp.optional": ("opcional", "optional", "opcional"),
"insp.options": ("Opções", "Options", "Opciones"),
"insp.correct": ("correta", "correct", "correcta"),
"insp.addOption": ("Adicionar opção", "Add option", "Añadir opción"),
"insp.addQuestion": ("Adicionar pergunta", "Add question", "Añadir pregunta"),
"insp.feedback": ("Feedback", "Feedback", "Retroalimentación"),
"insp.instructions": ("Instruções", "Instructions", "Instrucciones"),
"insp.fieldN": ("Campo {n}", "Field {n}", "Campo {n}"),
"insp.fieldType": ("Tipo do campo", "Field type", "Tipo de campo"),
"insp.label": ("Rótulo", "Label", "Etiqueta"),
"insp.required": ("Obrigatório", "Required", "Obligatorio"),
"insp.min-words": ("Mínimo de palavras", "Minimum words", "Mínimo de palabras"),
"insp.max-words": ("Máximo de palavras", "Maximum words", "Máximo de palabras"),
"insp.addField": ("Adicionar campo", "Add field", "Añadir campo"),
"insp.state": ("State (o que a IA julga)", "State (what the AI judges)", "State (lo que juzga la IA)"),
"insp.stateList": ("lista de textos", "list of texts", "lista de textos"),
"insp.stateListHint": ("Um campo pode ser um texto ou uma lista de textos", "A field may be a text or a list of texts", "Un campo puede ser un texto o una lista de textos"),
"insp.addText": ("Adicionar texto", "Add text", "Añadir texto"),
"insp.addStateField": ("Adicionar campo ao state", "Add a state field", "Añadir campo al state"),
"insp.judgeInstructions": ("Instruções (a pergunta que a IA responde)", "Instructions (the question the AI answers)", "Instrucciones (la pregunta que responde la IA)"),
"insp.choiceOptions": ("Opções (nome → descrição)", "Options (name → description)", "Opciones (nombre → descripción)"),
"insp.noDescription": ("sem descrição (null)", "no description (null)", "sin descripción (null)"),
"insp.nullHint": ("Descrição nula: o nome basta", "Null description: the name says it all", "Descripción nula: el nombre basta"),
"insp.unclearHint": ("Recomendado: uma opção como 'unclear', para quando nenhuma outra servir.", "Recommended: an option such as 'unclear', for when none of the others fits.", "Recomendado: una opción como 'unclear', para cuando ninguna otra sirva."),
"insp.levels": ("Níveis da escala (do mais baixo ao mais alto)", "Levels of the scale (lowest to highest)", "Niveles de la escala (del más bajo al más alto)"),
"insp.points": ("Pontos por nível", "Points per level", "Puntos por nivel"),
"insp.addLevel": ("Adicionar nível", "Add level", "Añadir nivel"),
"insp.levelHint": ("O nível vai de 0 a {max} e não é inteiro: compare com gt/gte/lt/lte, não com eq.", "The level runs from 0 to {max} and is not a whole number: compare it with gt/gte/lt/lte, not eq.", "El nivel va de 0 a {max} y no es entero: compárelo con gt/gte/lt/lte, no con eq."),
"insp.noulCriteria": ("O que conta como sim e como não", "What counts as yes and as no", "Qué cuenta como sí y como no"),
# edges / conditions
"edges.outgoing": ("Edges que saem deste nó", "Edges leaving this node", "Aristas que salen de este nodo"),
"edges.none": ("Nenhuma edge sai deste nó: ele termina o curso.", "No edge leaves this node: it ends the course.", "Ninguna arista sale de este nodo: termina el curso."),
"edges.fallback": ("sempre (fallback)", "always (fallback)", "siempre (fallback)"),
"edges.orderHint": ("A ordem importa: o player segue a primeira edge cuja condição vale. A edge sem condição vai por último.", "Order matters: the player takes the first edge whose condition holds. The edge without a condition goes last.", "El orden importa: el player sigue la primera arista cuya condición se cumple. La arista sin condición va al final."),
"edges.edge": ("Edge", "Edge", "Arista"),
"edges.from": ("De", "From", "Desde"),
"edges.to": ("Para", "To", "Hacia"),
"edges.position": ("Posição na ordem de avaliação", "Position in evaluation order", "Posición en el orden de evaluación"),
"edges.condition": ("Condição (when)", "Condition (when)", "Condición (when)"),
"edges.makeFallback": ("Remover a condição (virar fallback)", "Remove the condition (make it the fallback)", "Quitar la condición (convertirla en fallback)"),
"edges.isFallback": ("Sem condição: é a edge de fallback, tomada quando nenhuma anterior vale.", "No condition: this is the fallback, taken when none of the earlier ones holds.", "Sin condición: es la arista de fallback, tomada cuando ninguna anterior se cumple."),
"edges.addCondition": ("Adicionar condição", "Add condition", "Añadir condición"),
"cond.joiner": ("Junção", "Joiner", "Unión"),
"cond.and": ("E (and)", "AND", "Y (and)"),
"cond.or": ("OU (or)", "OR", "O (or)"),
"cond.allHint": ("todas valem", "all hold", "todas se cumplen"),
"cond.anyHint": ("ao menos uma vale", "at least one holds", "al menos una se cumple"),
"cond.invert": ("inverter", "invert", "invertir"),
"cond.invertHint": ("Não existe 'not': inverte cada operador (≥ vira <) e troca and/or (De Morgan).", "There is no 'not': flips each operator (≥ becomes <) and swaps and/or (De Morgan).", "No existe 'not': invierte cada operador (≥ pasa a <) e intercambia and/or (De Morgan)."),
"cond.unwrap": ("desagrupar", "unwrap", "desagrupar"),
"cond.groupNeedsTwo": ("Um grupo precisa de pelo menos duas condições.", "A group needs at least two conditions.", "Un grupo necesita al menos dos condiciones."),
"cond.addComparison": ("Comparação", "Comparison", "Comparación"),
"cond.addGroup": ("Grupo", "Group", "Grupo"),
"cond.pickKey": ("escolha uma chave", "pick a key", "elija una clave"),
"cond.wrap": ("agrupar", "group", "agrupar"),
"cond.wrapHint": ("Coloca esta comparação num grupo and/or com outra", "Puts this comparison in an and/or group with another", "Pone esta comparación en un grupo and/or con otra"),
"cond.fromAi": ("gerado pela IA", "produced by the AI", "generado por la IA"),
"cond.warnEqAi": ("Evite eq/ne num número gerado pela IA: ele raramente é exato. Use gt, gte, lt ou lte.", "Avoid eq/ne on a number the AI produced: it is rarely exact. Use gt, gte, lt or lte.", "Evite eq/ne con un número generado por la IA: rara vez es exacto. Use gt, gte, lt o lte."),
"cond.warnLevel": ("Este nível vai de 0 a {max}; o valor nunca será alcançado. Para nota de 0 a 100 use pontos e {node}.percent.", "This level runs from 0 to {max}; the value is never reached. For a grade out of 100 use points and {node}.percent.", "Este nivel va de 0 a {max}; el valor nunca se alcanza. Para nota de 0 a 100 use puntos y {node}.percent."),
"cond.warnUnit": ("Esta chave vai de 0 a 1.", "This key runs from 0 to 1.", "Esta clave va de 0 a 1."),
"cond.warnPercent": ("Esta chave vai de 0 a 100.", "This key runs from 0 to 100.", "Esta clave va de 0 a 100."),
"cond.warnNotNumber": ("Esta chave é numérica: o valor deveria ser um número.", "This key is numeric: the value should be a number.", "Esta clave es numérica: el valor debería ser un número."),
"cond.warnBool": ("Para uma resposta sim/não, compare com true ou false de verdade.", "For a yes/no answer, compare with a real true or false.", "Para una respuesta sí/no, compare con true o false reales."),
"cond.warnUnknownKey": ("Nenhum nó produz esta chave.", "No node produces this key.", "Ningún nodo produce esta clave."),
"scale.percent": ("Percentual", "Percentage", "Porcentaje"),
"scale.unit": ("Probabilidade / confiança", "Probability / confidence", "Probabilidad / confianza"),
"scale.level": ("Nível", "Level", "Nivel"),
"scale.count": ("Contagem", "Count", "Conteo"),
"scale.points": ("Pontos", "Points", "Puntos"),
"scale.option": ("Opção", "Option", "Opción"),
"scale.list": ("Lista", "List", "Lista"),
"scale.bool": ("Booleano", "Boolean", "Booleano"),
"scale.text": ("Texto", "Text", "Texto"),
"prompt.insertKey": ("Inserir {{STORAGE: …}}", "Insert {{STORAGE: …}}", "Insertar {{STORAGE: …}}"),
# localized fields
"loc.compare": ("comparar idiomas", "compare languages", "comparar idiomas"),
"loc.preview": ("visualizar", "preview", "vista previa"),
"loc.promptPlaceholder": ("Prompt em inglês; pode ler {{STORAGE: chave}}. Digite {{ para ver as chaves.", "Prompt in English; may read {{STORAGE: key}}. Type {{ to see the keys.", "Prompt en inglés; puede leer {{STORAGE: clave}}. Escriba {{ para ver las claves."),
"loc.optionalLang": ("Opcional: prompts costumam existir num só idioma.", "Optional: prompts usually exist in one language only.", "Opcional: los prompts suelen existir en un solo idioma."),
"pair.title": ("Tarefa de escrita: {form} ↔ state", "Writing task: {form} ↔ state", "Tarea de escritura: {form} ↔ state"),
"pair.assignment": ("Instruções de {form}", "Instructions of {form}", "Instrucciones de {form}"),
"pair.state": ("State deste julgamento", "State of this judgement", "State de este juicio"),
"pair.formChanged": ("As instruções de {form} mudaram, mas o state não. Confira se o julgamento ainda pede a mesma tarefa.", "The instructions of {form} changed but the state did not. Check that the judgement still asks for the same task.", "Las instrucciones de {form} cambiaron pero el state no. Compruebe que el juicio sigue pidiendo la misma tarea."),
"pair.stateChanged": ("O state mudou, mas as instruções de {form} não. Confira se o estudante ainda é avisado do que será julgado.", "The state changed but the instructions of {form} did not. Check that the student is still told what will be judged.", "El state cambió pero las instrucciones de {form} no. Compruebe que el estudiante sigue sabiendo qué se juzgará."),
"pair.mark": ("Marcar como alinhados", "Mark as matching", "Marcar como alineados"),
# course info
"course.info": ("Informações do curso", "Course information", "Información del curso"),
"course.title": ("Título do curso", "Course title", "Título del curso"),
"course.description": ("Descrição", "Description", "Descripción"),
"course.author": ("Autor", "Author", "Autor"),
"course.version": ("Versão", "Version", "Versión"),
"course.date": ("Data", "Date", "Fecha"),
"course.start": ("Nó de início", "Start node", "Nodo de inicio"),
"course.newId": ("Novo UUID", "New UUID", "Nuevo UUID"),
"course.newIdHint": ("Gera outro course-id: use só ao criar um curso derivado", "Generates another course-id: only for a derived course", "Genera otro course-id: solo para un curso derivado"),
"course.languages": ("Idiomas", "Languages", "Idiomas"),
"course.manageLanguages": ("Idiomas do curso…", "Course languages…", "Idiomas del curso…"),
"course.systemPrompt": ("System prompt", "System prompt", "System prompt"),
"course.sections": ("Seções", "Sections", "Secciones"),
"course.sectionTitle": ("Título da seção {n}", "Title of section {n}", "Título de la sección {n}"),
"course.addSection": ("Adicionar seção", "Add section", "Añadir sección"),
# languages
"lang.title": ("Idiomas do curso", "Course languages", "Idiomas del curso"),
"lang.code": ("Código", "Code", "Código"),
"lang.name": ("Nome", "Name", "Nombre"),
"lang.coverage": ("Textos preenchidos", "Texts filled", "Textos completos"),
"lang.source": ("origem", "source", "origen"),
"lang.rename": ("Renomear", "Rename", "Renombrar"),
"lang.renamePrompt": ("Novo código para {lang} (ex.: pt-BR):", "New code for {lang} (e.g. pt-BR):", "Nuevo código para {lang} (p. ej. pt-BR):"),
"lang.makeSource": ("Tornar origem", "Make source", "Convertir en origen"),
"lang.remove": ("Remover idioma", "Remove language", "Quitar idioma"),
"lang.removeConfirm": ("Remover o idioma {lang} apaga os textos dele em todo o curso, prompts incluídos. Continuar?", "Removing {lang} deletes its texts across the whole course, prompts included. Continue?", "Quitar {lang} borra sus textos en todo el curso, prompts incluidos. ¿Continuar?"),
"lang.add": ("Adicionar idioma", "Add language", "Añadir idioma"),
"lang.search": ("Buscar: código ISO 639-1 ou nome", "Search: ISO 639-1 code or name", "Buscar: código ISO 639-1 o nombre"),
"lang.region": ("Região", "Region", "Región"),
"lang.addHint": ("Adicionar um idioma cria uma entrada vazia em cada texto que o estudante lê; o inspetor marca as que faltam e o tradutor pode preenchê-las.", "Adding a language opens an empty entry in every text the student reads; the inspector marks the missing ones and the translator can fill them.", "Añadir un idioma crea una entrada vacía en cada texto que lee el estudiante; el inspector marca las que faltan y el traductor puede completarlas."),
# problems / json
"problems.title": ("Problemas", "Problems", "Problemas"),
"problems.all": ("Todos", "All", "Todos"),
"problems.error": ("Erros", "Errors", "Errores"),
"problems.warning": ("Avisos", "Warnings", "Avisos"),
"problems.clean": ("O curso é válido: nenhum erro, nenhum aviso.", "The course is valid: no errors, no warnings.", "El curso es válido: sin errores ni avisos."),
"problems.noneHere": ("Nada neste filtro.", "Nothing in this filter.", "Nada en este filtro."),
"problems.copy": ("Copiar relatório", "Copy report", "Copiar informe"),
"problems.copyHint": ("Copia as linhas como o validate_course.py imprime", "Copies the lines as validate_course.py prints them", "Copia las líneas como las imprime validate_course.py"),
"json.invalid": ("JSON inválido (não aplicado)", "Invalid JSON (not applied)", "JSON inválido (no aplicado)"),
"json.notObject": ("o curso precisa ser um objeto", "the course must be an object", "el curso debe ser un objeto"),
# ajv
"ajv.required": ("falta o campo obrigatório '{field}'", "missing required field '{field}'", "falta el campo obligatorio '{field}'"),
"ajv.additional": ("campo desconhecido '{field}' (o formato não aceita campos extras)", "unknown field '{field}' (the format allows no extra fields)", "campo desconocido '{field}' (el formato no admite campos extra)"),
"ajv.pattern": ("não segue o padrão {pattern}", "does not match the pattern {pattern}", "no sigue el patrón {pattern}"),
"ajv.start": ("o início não pode ser um nó choice, score ou noul: no início não há nada a julgar", "the start cannot be a choice, score or noul node: at the start there is nothing to judge", "el inicio no puede ser un nodo choice, score o noul: al inicio no hay nada que juzgar"),
"ajv.type": ("deveria ser do tipo {type}", "should be of type {type}", "debería ser de tipo {type}"),
"ajv.enum": ("deveria ser um de: {values}", "should be one of: {values}", "debería ser uno de: {values}"),
"ajv.const": ("deveria ser {value}", "should be {value}", "debería ser {value}"),
"ajv.minItems": ("precisa de pelo menos {limit} itens", "needs at least {limit} items", "necesita al menos {limit} elementos"),
"ajv.maxItems": ("aceita no máximo {limit} itens", "takes at most {limit} items", "admite como máximo {limit} elementos"),
"ajv.minProperties": ("precisa de pelo menos {limit} entradas", "needs at least {limit} entries", "necesita al menos {limit} entradas"),
"ajv.maxProperties": ("aceita no máximo {limit} entradas", "takes at most {limit} entries", "admite como máximo {limit} entradas"),
"ajv.minLength": ("não pode ser vazio", "must not be empty", "no puede estar vacío"),
"ajv.minimum": ("deveria ser no mínimo {limit}", "should be at least {limit}", "debería ser como mínimo {limit}"),
"ajv.format": ("não é um {format} válido", "is not a valid {format}", "no es un {format} válido"),
"ajv.unique": ("tem itens repetidos", "has repeated items", "tiene elementos repetidos"),
"ajv.oneCorrect": ("exatamente uma opção deve ter correct: true", "exactly one option must have correct: true", "exactamente una opción debe tener correct: true"),
"ajv.condition": ("condição inválida: use uma comparação {key, operator, value} ou um grupo and/or com duas ou mais condições", "invalid condition: use a comparison {key, operator, value} or an and/or group with two or more conditions", "condición inválida: use una comparación {key, operator, value} o un grupo and/or con dos o más condiciones"),
"ajv.not": ("valor não permitido aqui (nome reservado, ou campo que não cabe neste tipo)", "value not allowed here (a reserved name, or a field that does not fit this type)", "valor no permitido aquí (nombre reservado, o campo que no corresponde a este tipo)"),
"ajv.propertyName": ("nome inválido: letras minúsculas, dígitos e hífens", "invalid name: lowercase letters, digits and hyphens", "nombre inválido: minúsculas, dígitos y guiones"),
# validation (rule.*: the en column is validate_course.py's own words, as in src/validate/rules.ts)
"rule.translations": ("{count} texto(s) sem versão em '{lang}' ({sample})", "{count} text(s) have no '{lang}' version ({sample})", "{count} texto(s) sin versión en '{lang}' ({sample})"),
"rule.translations-more": ("{count} texto(s) sem versão em '{lang}' ({sample} e mais {more})", "{count} text(s) have no '{lang}' version ({sample} and {more} more)", "{count} texto(s) sin versión en '{lang}' ({sample} y {more} más)"),
"rule.not-object": ("deveria ser um objeto, mas é {type}", "expected an object, found {type}", "debería ser un objeto, pero es {type}"),
"rule.missing-field": ("falta o campo obrigatório '{key}'", "missing required field '{key}'", "falta el campo obligatorio '{key}'"),
"rule.unknown-field": ("campo desconhecido '{key}' (o formato não aceita campos extras)", "unknown field '{key}' (the format allows no extra fields)", "campo desconocido '{key}' (el formato no admite campos extra)"),
"rule.localized-list": ("{label}: precisa ser uma lista não vazia de objetos {lang, text}", "{label} must be a non-empty list of {lang, text} objects", "{label}: debe ser una lista no vacía de objetos {lang, text}"),
"rule.localized-entry": ("cada entrada precisa ser um objeto com 'lang' e 'text'", "each entry must be an object with 'lang' and 'text'", "cada entrada debe ser un objeto con 'lang' y 'text'"),
"rule.unknown-fields": ("campo(s) desconhecido(s) {fields}", "unknown field(s) {fields}", "campo(s) desconocido(s) {fields}"),
"rule.lang-code-example": ("código de idioma inválido {value} (exemplos: 'pt', 'en', 'pt-BR')", "invalid language code {value} (expected e.g. 'pt', 'en', 'pt-BR')", "código de idioma inválido {value} (ejemplos: 'pt', 'en', 'pt-BR')"),
"rule.lang-twice": ("o idioma '{lang}' aparece duas vezes", "language '{lang}' appears twice", "el idioma '{lang}' aparece dos veces"),
"rule.lang-undeclared": ("o idioma '{lang}' não está declarado em info", "language '{lang}' is not declared in info", "el idioma '{lang}' no está declarado en info"),
"rule.text-string": ("'text' precisa ser uma string", "'text' must be a string", "'text' debe ser una cadena"),
"rule.text-empty": ("{label} sem texto", "empty {label}", "{label} sin texto"),
"rule.source-missing": ("falta o idioma de origem '{lang}'", "missing the source language '{lang}'", "falta el idioma de origen '{lang}'"),
"rule.lang-code": ("código de idioma inválido {value}", "invalid language code {value}", "código de idioma inválido {value}"),
"rule.other-languages-list": ("precisa ser uma lista (use [] quando não houver traduções)", "must be a list (use [] when there are no translations)", "debe ser una lista (use [] cuando no haya traducciones)"),
"rule.lang-is-source": ("'{lang}' é o idioma de origem e não deve ser repetido aqui", "'{lang}' is the source language and must not be repeated here", "'{lang}' es el idioma de origen y no debe repetirse aquí"),
"rule.lang-repeated": ("'{lang}' aparece duas vezes", "'{lang}' appears twice", "'{lang}' aparece dos veces"),
"rule.uuid": ("precisa ser um UUID; encontrado {value}", "must be a UUID, found {value}", "debe ser un UUID; se encontró {value}"),
"rule.non-empty-string": ("precisa ser um texto não vazio", "must be a non-empty string", "debe ser un texto no vacío"),
"rule.version": ("precisa estar no formato MAJOR.MINOR.PATCH; encontrado {value}", "must be MAJOR.MINOR.PATCH, found {value}", "debe tener el formato MAJOR.MINOR.PATCH; se encontró {value}"),
"rule.date-format": ("precisa estar no formato AAAA-MM-DD; encontrado {value}", "must be YYYY-MM-DD, found {value}", "debe tener el formato AAAA-MM-DD; se encontró {value}"),
"rule.date-real": ("precisa ser uma data que existe; encontrado {value}", "must be a real date, found {value}", "debe ser una fecha que exista; se encontró {value}"),
"rule.start-id": ("id de nó inválido {value}", "invalid node id {value}", "id de nodo inválido {value}"),
"rule.list": ("precisa ser uma lista", "must be a list", "debe ser una lista"),
"rule.section-number": ("'number' precisa ser um inteiro >= 1; encontrado {value}", "'number' must be an integer >= 1, found {value}", "'number' debe ser un entero >= 1; se encontró {value}"),
"rule.section-twice": ("a seção número {number} está declarada duas vezes", "section number {number} is declared twice", "la sección número {number} está declarada dos veces"),
"rule.system-prompt-language": ("não menciona o idioma do estudante; acrescente 'Answer in the student's language.'", "does not mention the student's language; add 'Answer in the student's language.'", "no menciona el idioma del estudiante; agregue 'Answer in the student's language.'"),
"rule.quiz-empty": ("um quiz precisa de pelo menos uma pergunta", "a quiz needs at least one question", "un cuestionario necesita al menos una pregunta"),
"rule.key-name": ("'key' inválida {value} (letras minúsculas, dígitos e hífens)", "invalid 'key' {value} (lowercase letters, digits and hyphens)", "'key' inválida {value} (minúsculas, dígitos y guiones)"),
"rule.quiz-key-reserved": ("'key' não pode ser '{key}': o quiz já produz essa chave", "'key' cannot be '{key}' — the quiz already produces it", "'key' no puede ser '{key}': el cuestionario ya produce esa clave"),
"rule.quiz-key-twice": ("a chave '{key}' é usada duas vezes neste quiz", "key '{key}' is used twice in this quiz", "la clave '{key}' se usa dos veces en este cuestionario"),
"rule.question-options": ("uma pergunta precisa de pelo menos duas opções", "a question needs at least two options", "una pregunta necesita al menos dos opciones"),
"rule.value-name": ("'value' inválido {value} (letras minúsculas, dígitos e hífens)", "invalid 'value' {value} (lowercase letters, digits and hyphens)", "'value' inválido {value} (minúsculas, dígitos y guiones)"),
"rule.question-value-twice": ("o valor de opção '{value}' é usado duas vezes nesta pergunta", "option value '{value}' is used twice in this question", "el valor de opción '{value}' se usa dos veces en esta pregunta"),
"rule.correct-bool": ("'correct' precisa ser true ou false", "'correct' must be true or false", "'correct' debe ser true o false"),
"rule.one-correct": ("exatamente uma opção deve ser a correta; há {count}", "exactly one option must be correct, found {count}", "exactamente una opción debe ser la correcta; hay {count}"),
"rule.spread-all": ("a resposta certa é a opção {letter} em todas as perguntas {scope}: embaralhe as opções", "the correct answer is option {letter} in every question of {scope} — shuffle the options", "la respuesta correcta es la opción {letter} en todas las preguntas {scope}: mezcle las opciones"),
"rule.spread-most": ("a resposta certa é a opção {letter} em {hits} de {total} perguntas {scope}: distribua melhor", "the correct answer is option {letter} in {hits} of {total} questions of {scope} — spread it out", "la respuesta correcta es la opción {letter} en {hits} de {total} preguntas {scope}: distribúyala mejor"),
"rule.form-empty": ("um formulário precisa de pelo menos um campo", "a form needs at least one field", "un formulario necesita al menos un campo"),
"rule.form-assignment": ("um único text-area e nenhuma 'instructions': uma tarefa de escrita precisa do enunciado (o que escrever, com que tamanho e o que será avaliado)", "a single text-area and no 'instructions': a writing task needs its assignment -- what to write, how long, and what will be judged", "un único text-area y ninguna 'instructions': una tarea de escritura necesita su consigna (qué escribir, con qué extensión y qué se evaluará)"),
"rule.form-key-twice": ("a chave de campo '{key}' é usada duas vezes neste formulário", "field key '{key}' is used twice in this form", "la clave de campo '{key}' se usa dos veces en este formulario"),
"rule.field-type": ("tipo de campo inválido {value} (um de {allowed})", "invalid field type {value} (one of {allowed})", "tipo de campo inválido {value} (uno de {allowed})"),
"rule.required-bool": ("'required' precisa ser true ou false", "'required' must be true or false", "'required' debe ser true o false"),
"rule.words-not-counted": ("um campo '{type}' não conta palavras, então não aceita '{bound}'", "a '{type}' field counts no words, so it takes no '{bound}'", "un campo '{type}' no cuenta palabras, así que no admite '{bound}'"),
"rule.words-whole": ("'{bound}' precisa ser um número inteiro >= 1; encontrado {value}", "'{bound}' must be a whole number >= 1, found {value}", "'{bound}' debe ser un número entero >= 1; se encontró {value}"),
"rule.words-crossed": ("'max-words' ({max}) é menor que 'min-words' ({min}): nenhuma resposta satisfaz os dois", "'max-words' ({max}) is below 'min-words' ({min}): no answer can satisfy both", "'max-words' ({max}) es menor que 'min-words' ({min}): ninguna respuesta cumple ambos"),
"rule.field-options": ("um campo '{type}' precisa de pelo menos duas opções", "a '{type}' field needs at least two options", "un campo '{type}' necesita al menos dos opciones"),
"rule.value-invalid": ("'value' inválido {value}", "invalid 'value' {value}", "'value' inválido {value}"),
"rule.field-value-twice": ("o valor de opção '{value}' é usado duas vezes neste campo", "option value '{value}' is used twice in this field", "el valor de opción '{value}' se usa dos veces en este campo"),
"rule.field-no-options": ("um campo '{type}' não deve ter opções", "a '{type}' field must not have options", "un campo '{type}' no debe tener opciones"),
"rule.points-list": ("precisa ser uma lista de números, um por nível de 'criteria'", "must be a list of numbers, one per level of 'criteria'", "debe ser una lista de números, uno por nivel de 'criteria'"),
"rule.number": ("precisa ser um número; encontrado {value}", "must be a number, found {value}", "debe ser un número; se encontró {value}"),
"rule.non-negative": ("precisa ser 0 ou mais; encontrado {value}", "must be 0 or more, found {value}", "debe ser 0 o más; se encontró {value}"),
"rule.points-count": ("{points} valor(es) de pontos para {levels} nível(is): precisa haver exatamente um por nível, na mesma ordem", "{points} point value(s) for {levels} level(s): there must be exactly one per level, in the same order", "{points} valor(es) de puntos para {levels} nivel(es): debe haber exactamente uno por nivel, en el mismo orden"),
"rule.points-order": ("os pontos não sobem com os níveis ({points}): um nível mais alto valendo menos que um mais baixo quase sempre é erro de digitação", "the points do not rise with the levels ({points}): a higher level worth less than a lower one is almost always a typo", "los puntos no suben con los niveles ({points}): un nivel más alto que vale menos que uno más bajo casi siempre es un error de tipeo"),
"rule.choice-criteria": ("precisa ser um mapa do nome de cada opção para o que ela abrange", "must be a map of the name of each option to what it covers", "debe ser un mapa del nombre de cada opción a lo que abarca"),
"rule.choice-few": ("uma escolha precisa de pelo menos duas opções", "a choice needs at least two options", "una elección necesita al menos dos opciones"),
"rule.choice-many": ("uma escolha aceita no máximo 255 opções; há {count}", "a choice takes at most 255 options, got {count}", "una elección admite como máximo 255 opciones; hay {count}"),
"rule.choice-option-name": ("a opção '{name}' precisa ser um nome que as edges possam comparar: letras minúsculas, dígitos e -", "the option '{name}' must be a name the edges can compare to: lowercase letters, digits and -", "la opción '{name}' debe ser un nombre que las aristas puedan comparar: minúsculas, dígitos y -"),
"rule.choice-option-text": ("precisa ser um texto dizendo o que a opção abrange, ou null", "must be a text saying what the option covers, or null", "debe ser un texto que diga lo que abarca la opción, o null"),
"rule.score-criteria": ("precisa ser a lista dos níveis da escala, em ordem, do mais baixo ao mais alto", "must be the levels of the scale, in order, from the low end to the high end", "debe ser la lista de niveles de la escala, en orden, del más bajo al más alto"),
"rule.score-levels": ("uma escala tem entre 2 e 10 níveis; há {count}", "a scale has between 2 and 10 levels, got {count}", "una escala tiene entre 2 y 10 niveles; hay {count}"),
"rule.score-level-text": ("cada nível precisa dizer o que significa", "each level must say what it means", "cada nivel debe decir lo que significa"),
"rule.noul-criteria": ("precisa dizer o que 'true' e o que 'false' abrangem", "must say what 'true' and what 'false' cover", "debe decir lo que abarcan 'true' y 'false'"),
"rule.noul-criteria-field": ("'{name}' não é um campo aqui: só 'true' e 'false' são", "'{name}' is not a field here: only 'true' and 'false' are", "'{name}' no es un campo aquí: solo lo son 'true' y 'false'"),
"rule.non-empty-text": ("precisa ser um texto não vazio", "must be a non-empty text", "debe ser un texto no vacío"),
"rule.state-object": ("o estado que a IA julga precisa ser um objeto de campos nomeados, por exemplo {\"task\": \"...\", \"answer\": \"{{STORAGE: f1.text}}\"}", "the state the AI judges must be an object of named fields, e.g. {\"task\": \"...\", \"answer\": \"{{STORAGE: f1.text}}\"}", "el estado que juzga la IA debe ser un objeto de campos con nombre, por ejemplo {\"task\": \"...\", \"answer\": \"{{STORAGE: f1.text}}\"}"),
"rule.state-field-name": ("um nome de campo usa letras minúsculas, dígitos e hífens", "a field name is lowercase letters, digits and hyphens", "un nombre de campo usa minúsculas, dígitos y guiones"),
"rule.text": ("precisa ser um texto", "must be a text", "debe ser un texto"),
"rule.text-or-list": ("precisa ser um texto ou uma lista de textos", "must be a text, or a list of texts", "debe ser un texto o una lista de textos"),
"rule.state-no-storage": ("o estado não lê nenhum {{STORAGE: key}}, então a IA julga a mesma coisa para todo estudante e o nó sempre toma a mesma edge", "the state reads no {{STORAGE: key}}, so the AI judges the same thing for every student and the node always takes the same edge", "el estado no lee ningún {{STORAGE: key}}, así que la IA juzga lo mismo para todos los estudiantes y el nodo siempre toma la misma arista"),
"rule.judge-empty": ("um nó de julgamento precisa de pelo menos uma pergunta", "a judgement node needs at least one question", "un nodo de juicio necesita al menos una pregunta"),
"rule.judge-key": ("precisa ser um nome como 'track': letras minúsculas, dígitos e -", "must be a name like 'track': lowercase letters, digits and -", "debe ser un nombre como 'track': minúsculas, dígitos y -"),
"rule.judge-key-suffix": ("não pode terminar em '{suffix}': o nó produz essa chave sozinho", "cannot end in '{suffix}': the node produces that key on its own", "no puede terminar en '{suffix}': el nodo produce esa clave por sí mismo"),
"rule.judge-key-reserved": ("'{key}' é o que um nó score produz para o nó inteiro; dê à pergunta o nome do que ela julga", "'{key}' is what a score node produces for the whole node; name the question after what it judges", "'{key}' es lo que un nodo score produce para el nodo entero; nombre la pregunta según lo que juzga"),
"rule.judge-key-twice": ("'{key}' é usada duas vezes no mesmo nó", "'{key}' is used twice in the same node", "'{key}' se usa dos veces en el mismo nodo"),
"rule.judge-instructions": ("a pergunta que a IA responde precisa ser um texto não vazio", "the question the AI answers must be a non-empty string", "la pregunta que responde la IA debe ser un texto no vacío"),
"rule.node-object": ("cada nó precisa ser um objeto", "each node must be an object", "cada nodo debe ser un objeto"),
"rule.node-type": ("tipo inválido {value} (um de {allowed})", "invalid type {value} (one of {allowed})", "tipo inválido {value} (uno de {allowed})"),
"rule.node-id": ("id inválido {value}", "invalid id {value}", "id inválido {value}"),
"rule.node-id-twice": ("dois nós usam este id", "two nodes use this id", "dos nodos usan este id"),
"rule.node-prefix": ("o id não combina com o tipo '{type}' (prefixo esperado: '{prefix}')", "id does not match type '{type}' (expected prefix '{prefix}')", "el id no corresponde al tipo '{type}' (prefijo esperado: '{prefix}')"),
"rule.node-section": ("'section' precisa ser um inteiro >= 1; encontrado {value}", "'section' must be an integer >= 1, found {value}", "'section' debe ser un entero >= 1; se encontró {value}"),
"rule.section-undeclared": ("a seção {number} não está declarada em info.sections", "section {number} is not declared in info.sections", "la sección {number} no está declarada en info.sections"),
"rule.content-short": ("o conteúdo é curto demais ({count} palavras) para um nó de ensino", "content is very short ({count} words) for a teaching node", "el contenido es demasiado corto ({count} palabras) para un nodo de enseñanza"),
"rule.from-id": ("precisa ser o id de um nó choice, score ou noul; encontrado {value}", "must be the id of a choice, score or noul node, found {value}", "debe ser el id de un nodo choice, score o noul; se encontró {value}"),
"rule.from-judging": ("escreve a partir do julgamento de {judge}, mas o prompt diz '{word}': o nível já está decidido, e um feedback que julga de novo pode contradizer o número que encaminhou o estudante; diga como escrever, não o que decidir", "writes from the judgement of {judge} but its prompt says '{word}': the level is already settled, and a feedback that judges again can contradict the number that routed the student -- tell it how to write, not what to decide", "escribe a partir del juicio de {judge}, pero su prompt dice '{word}': el nivel ya está decidido, y un feedback que vuelve a juzgar puede contradecir el número que encaminó al estudiante; diga cómo escribir, no qué decidir"),
"rule.dynamic-static": ("nó dinâmico cujo prompt não lê nenhum {{STORAGE: key}}: nada o personaliza; considere torná-lo estático", "dynamic node whose prompt reads no {{STORAGE: key}} — nothing personalises it, consider making it static", "nodo dinámico cuyo prompt no lee ningún {{STORAGE: key}}: nada lo personaliza; considere hacerlo estático"),
"rule.true-false": ("precisa ser true ou false", "must be true or false", "debe ser true o false"),
"rule.condition-deep": ("condição aninhada fundo demais", "condition nested too deeply", "condición anidada a demasiada profundidad"),
"rule.when-object": ("'when' precisa ser um objeto", "'when' must be an object", "'when' debe ser un objeto"),
"rule.group-only": ("uma condição '{joiner}' deve conter só '{joiner}'; encontrado {fields}", "an '{joiner}' condition must contain only '{joiner}', found {fields}", "una condición '{joiner}' debe contener solo '{joiner}'; se encontró {fields}"),
"rule.group-list": ("precisa ser uma lista de pelo menos duas condições", "must be a list of at least two conditions", "debe ser una lista de al menos dos condiciones"),
"rule.condition-unknown": ("campo(s) desconhecido(s) {fields} na condição", "unknown field(s) {fields} in condition", "campo(s) desconocido(s) {fields} en la condición"),
"rule.condition-missing": ("falta '{field}' na condição", "condition is missing '{field}'", "falta '{field}' en la condición"),
"rule.condition-key": ("chave inválida {value} (esperado '<id-do-nó>.<nome>', por exemplo 'q1.percent')", "invalid key {value} (expected '<node-id>.<name>', e.g. 'q1.percent')", "clave inválida {value} (se espera '<id-del-nodo>.<nombre>', por ejemplo 'q1.percent')"),
"rule.condition-operator": ("operador inválido {value} (um de {allowed})", "invalid operator {value} (one of {allowed})", "operador inválido {value} (uno de {allowed})"),
"rule.condition-value": ("'value' precisa ser uma string, um número ou um booleano", "'value' must be a string, number or boolean", "'value' debe ser una cadena, un número o un booleano"),
"rule.schema-string": ("precisa ser uma string (o endereço do schema)", "must be a string (the address of the schema)", "debe ser una cadena (la dirección del schema)"),
"rule.non-empty-list": ("precisa ser uma lista não vazia", "must be a non-empty list", "debe ser una lista no vacía"),
"rule.state-reads-mark": ("o campo de estado '{name}' lê '{key}', uma nota já dada: a IA se ancoraria nela em vez de julgar por si; dê ao julgamento o trabalho e a tarefa, não um veredito anterior", "the state field '{name}' reads '{key}', a mark already given: the AI would anchor on it instead of judging for itself -- give the judgement the work and the task, not an earlier verdict", "el campo de estado '{name}' lee '{key}', una nota ya dada: la IA se anclaría en ella en lugar de juzgar por sí misma; dé al juicio el trabajo y la tarea, no un veredicto anterior"),
"rule.from-missing": ("escreve a partir de '{from}', que não é um nó", "writes from '{from}', which is not a node", "escribe a partir de '{from}', que no es un nodo"),
"rule.from-not-judge": ("escreve a partir de '{from}', que é um nó {type} e não faz julgamento", "writes from '{from}', which is a {type} node and makes no judgement", "escribe a partir de '{from}', que es un nodo {type} y no hace ningún juicio"),
"rule.edge-from": ("'from' aponta para {value}, que não é um nó", "'from' points to {value}, which is not a node", "'from' apunta a {value}, que no es un nodo"),
"rule.edge-to": ("'to' aponta para {value}, que não é um nó", "'to' points to {value}, which is not a node", "'to' apunta a {value}, que no es un nodo"),
"rule.judge-no-fallback": ("todas as edges que saem são condicionais; um julgamento que a IA não conseguiu fazer deixa o estudante sem ter para onde ir: acrescente por último uma edge de fallback, sem condição", "every outgoing edge is conditional; a judgement the AI could not make leaves the student with nowhere to go — add an unconditional fallback edge last", "todas las aristas salientes son condicionales; un juicio que la IA no pudo hacer deja al estudiante sin adónde ir: agregue al final una arista de fallback, sin condición"),
"rule.no-fallback": ("todas as edges que saem são condicionais; um estudante que não se encaixe em nenhuma fica preso: acrescente por último uma edge de fallback, sem condição", "every outgoing edge is conditional; a student matching none of them gets stuck — add an unconditional fallback edge last", "todas las aristas salientes son condicionales; un estudiante que no cumpla ninguna queda atascado: agregue al final una arista de fallback, sin condición"),
"rule.fallbacks": ("{count} edges sem condição; só a primeira pode ser tomada", "{count} unconditional edges; only the first can ever be taken", "{count} aristas sin condición; solo la primera puede tomarse"),
"rule.fallback-not-last": ("a edge sem condição não é a última: as {count} edge(s) seguintes nunca são alcançadas", "the unconditional edge is not last: the following {count} edge(s) are unreachable", "la arista sin condición no es la última: las {count} arista(s) siguientes nunca se alcanzan"),
"rule.fallback-to-feedback": ("a edge sem condição leva a {target}, que escreve a partir deste mesmo julgamento; essa edge é o caminho tomado quando não houve julgamento, então {target} não teria do que escrever: mande o fallback para outro lugar", "its unconditional edge leads to {target}, which writes from this very judgement -- that edge is the path taken when no judgement was made, so {target} would have nothing to write from; send the fallback elsewhere", "su arista sin condición lleva a {target}, que escribe a partir de este mismo juicio; esa arista es el camino que se toma cuando no hubo juicio, así que {target} no tendría de qué escribir: envíe el fallback a otro lugar"),
"rule.unreachable": ("nenhum caminho a partir do nó inicial chega a: {nodes} (em geral, falta uma edge chegando neles)", "no path from the start node reaches: {nodes} (usually a missing edge into them)", "ningún camino desde el nodo inicial llega a: {nodes} (por lo general, falta una arista que llegue a ellos)"),
"rule.start-missing": ("o nó inicial '{start}' não existe", "start node '{start}' does not exist", "el nodo inicial '{start}' no existe"),
"rule.endings": ("vários nós terminam o curso: {nodes}; os ramos deveriam se reencontrar, a menos que cada um destes seja mesmo um final", "several nodes end the course: {nodes} — branches should reunite unless every one of these is a real ending", "varios nodos terminan el curso: {nodes}; las ramas deberían volver a unirse, a menos que cada uno de estos sea realmente un final"),
"rule.from-bypassed": ("escreve a partir do julgamento de {judge}, mas há um caminho até ele que nunca passa por {judge}: um estudante por esse caminho chegaria a um nó sem julgamento do qual escrever", "writes from the judgement of {judge}, but there is a path to it that never passes through {judge}: a student taking that path would reach a node with no judgement to write from", "escribe a partir del juicio de {judge}, pero hay un camino hasta él que nunca pasa por {judge}: un estudiante que tome ese camino llegaría a un nodo sin juicio del que escribir"),
"rule.key-unproduced": ("a condição lê '{key}', que nenhum nó produz", "condition reads '{key}', which no node produces", "la condición lee '{key}', que ningún nodo produce"),
"rule.key-not-upstream": ("'{key}' é produzida por {producer}, que não está em nenhum caminho até {reader}; esta condição nunca vale", "'{key}' is produced by {producer}, which is not on any path to {reader}; this condition can never hold", "'{key}' la produce {producer}, que no está en ningún camino hacia {reader}; esta condición nunca se cumple"),
"rule.key-levels": ("'{key}' vai de 0 a {top}, nos níveis da própria pergunta, então compará-la com {value} nunca vale. Para uma nota de 0 a 100, dê 'points' à pergunta e teste {owner}.percent", "'{key}' runs from 0 to {top}, over the levels of its own question, so comparing it against {value} never holds. For a grade out of 100 give the question 'points' and test {owner}.percent", "'{key}' va de 0 a {top}, en los niveles de su propia pregunta, así que compararla con {value} nunca se cumple. Para una nota de 0 a 100, dé 'points' a la pregunta y pruebe {owner}.percent"),
"rule.storage-invalid": ("{{STORAGE: {key}}} não é uma chave válida ('<id-do-nó>.<nome>')", "{{STORAGE: {key}}} is not a valid key ('<node-id>.<name>')", "{{STORAGE: {key}}} no es una clave válida ('<id-del-nodo>.<nombre>')"),
"rule.storage-unproduced": ("{{STORAGE: {key}}} lê uma chave que nenhum nó produz", "{{STORAGE: {key}}} reads a key no node produces", "{{STORAGE: {key}}} lee una clave que ningún nodo produce"),
"rule.storage-not-upstream": ("{{STORAGE: {key}}} é produzida por {producer}, que o estudante pode não ter alcançado antes de {node}; o valor ficará vazio", "{{STORAGE: {key}}} is produced by {producer}, which the student may not have reached before {node}; the value will be empty", "{{STORAGE: {key}}} la produce {producer}, que el estudiante puede no haber alcanzado antes de {node}; el valor quedará vacío"),
"rule.data-unused": ("guarda dados que nenhuma edge e nenhum prompt leem: crie um ramo a partir deles ou use-os num prompt", "stores data no edge and no prompt ever reads — branch on it or use it in a prompt", "guarda datos que ninguna arista ni ningún prompt leen: ramifique según ellos o úselos en un prompt"),
# validation: words inside the messages, the first word of where they point
"rule.word.title": ("título", "title", "título"),
"rule.word.description": ("descrição", "description", "descripción"),
"rule.word.section-title": ("título da seção", "section title", "título de la sección"),
"rule.word.question": ("pergunta", "question", "pregunta"),
"rule.word.feedback": ("feedback", "feedback", "feedback"),
"rule.word.option-label": ("rótulo da opção", "option label", "etiqueta de la opción"),
"rule.word.instructions": ("instruções", "instructions", "instrucciones"),
"rule.word.field-label": ("rótulo do campo", "field label", "etiqueta del campo"),
"rule.word.content": ("conteúdo", "content", "contenido"),
"rule.word.prompt": ("prompt", "prompt", "prompt"),
"rule.word.yes-label": ("rótulo do “sim”", "yes-label", "etiqueta del “sí”"),
"rule.word.no-label": ("rótulo do “não”", "no-label", "etiqueta del “no”"),
"rule.word.text": ("texto", "text", "texto"),
"rule.word.this-quiz": ("deste quiz", "this quiz", "de este cuestionario"),
"rule.word.the-whole-course": ("do curso inteiro", "the whole course", "de todo el curso"),
"where.node": ("nó", "node", "nodo"),
"where.edge": ("edge", "edge", "arista"),
"where.graph": ("grafo", "graph", "grafo"),
"where.translations": ("traduções", "translations", "traducciones"),
"where.quizzes": ("quizzes", "quizzes", "cuestionarios"),
"where.course": ("curso", "course", "curso"),
"ajv.other": ("não segue a regra '{keyword}' do schema", "does not follow the schema's '{keyword}' rule", "no cumple la regla '{keyword}' del schema"),
# errors: the AI calls of the preview (ai.why.*: ai.php's words in en), files, the native side
"json.at": ("erro de sintaxe na linha {line}, coluna {column}", "syntax error at line {line}, column {column}", "error de sintaxis en la línea {line}, columna {column}"),
"ai.empty": ("o modelo devolveu uma resposta vazia", "the model returned an empty answer", "el modelo devolvió una respuesta vacía"),
"ai.why.not-writer": ("o nó {node} não é um nó que a IA escreve", "node {node} is not a node the AI writes", "el nodo {node} no es un nodo que escriba la IA"),
"ai.why.no-prompt": ("o nó {node} não tem prompt", "node {node} has no prompt", "el nodo {node} no tiene prompt"),
"ai.why.not-judge": ("o nó {node} não é um nó que a IA julga", "node {node} is not a node the AI judges", "el nodo {node} no es un nodo que juzgue la IA"),
"ai.why.no-model": ("nenhum modelo de julgamento (judge.model) configurado.", "this server has no judge.model configured.", "no hay ningún modelo de juicio (judge.model) configurado."),
"ai.why.alias": ("judge.model \"{model}\" é um apelido, não uma versão.", "judge.model \"{model}\" is an alias, not a version.", "judge.model \"{model}\" es un alias, no una versión."),
"ai.why.not-unit": ("a pergunta \"{key}\" voltou com {value}, que não é um número de 0 a 1.", "question \"{key}\" came back with {value}, which is not a number from 0 to 1.", "la pregunta \"{key}\" volvió con {value}, que no es un número de 0 a 1."),
"ai.why.no-confidence": ("a pergunta \"{key}\" voltou sem confiança.", "question \"{key}\" came back without a confidence.", "la pregunta \"{key}\" volvió sin confianza."),
"ai.why.no-probabilities": ("a pergunta \"{key}\" voltou sem probabilidades.", "question \"{key}\" came back with no probabilities.", "la pregunta \"{key}\" volvió sin probabilidades."),
"ai.why.label-missing": ("a pergunta \"{key}\" deixou \"{label}\" fora das probabilidades.", "question \"{key}\" left \"{label}\" out of its probabilities.", "la pregunta \"{key}\" dejó \"{label}\" fuera de sus probabilidades."),
"ai.why.label-not-number": ("a pergunta \"{key}\" deu a \"{label}\" algo que não é um número.", "question \"{key}\" gave \"{label}\" something that is not a number.", "la pregunta \"{key}\" le dio a \"{label}\" algo que no es un número."),
"ai.why.label-unknown": ("a pergunta \"{key}\" pôs peso em \"{label}\", que não é um dos seus rótulos.", "question \"{key}\" put weight on \"{label}\", which is not one of its labels.", "la pregunta \"{key}\" puso peso en \"{label}\", que no es una de sus etiquetas."),
"ai.why.not-one": ("a pergunta \"{key}\" somou {sum}, não 1.", "question \"{key}\" added up to {sum}, not to 1.", "la pregunta \"{key}\" sumó {sum}, no 1."),
"ai.why.unanswered": ("a pergunta \"{key}\" não foi respondida.", "question \"{key}\" was not answered.", "la pregunta \"{key}\" no fue respondida."),
"ai.why.no-number": ("a pergunta \"{key}\" voltou sem número.", "question \"{key}\" came back without a number.", "la pregunta \"{key}\" volvió sin número."),
"ai.why.no-options": ("a pergunta \"{key}\" não tem opções com que ser respondida.", "question \"{key}\" has no options to be answered with.", "la pregunta \"{key}\" no tiene opciones con las que responderse."),
"ai.why.no-choice": ("a pergunta \"{key}\" não escolheu nada.", "question \"{key}\" chose nothing.", "la pregunta \"{key}\" no eligió nada."),
"ai.why.choice-unknown": ("a pergunta \"{key}\" respondeu \"{choice}\", que não é uma das suas opções.", "question \"{key}\" answered \"{choice}\", which is not one of its options.", "la pregunta \"{key}\" respondió \"{choice}\", que no es una de sus opciones."),
"ai.why.no-scale": ("a pergunta \"{key}\" não tem escala em que ser respondida.", "question \"{key}\" has no scale to be answered on.", "la pregunta \"{key}\" no tiene escala en la que responderse."),
"ai.why.no-level": ("a pergunta \"{key}\" voltou sem nível.", "question \"{key}\" came back without a level.", "la pregunta \"{key}\" volvió sin nivel."),
"ai.why.off-scale": ("a pergunta \"{key}\" voltou com {score}, fora de uma escala de {levels} níveis.", "question \"{key}\" came back at {score}, which is off a scale of {levels} levels.", "la pregunta \"{key}\" volvió con {score}, fuera de una escala de {levels} niveles."),
"ai.why.under-floor": ("a pergunta \"{key}\" voltou com confiança {sure}, abaixo do piso de {floor}.", "question \"{key}\" came back at {sure}, under this server's floor of {floor}.", "la pregunta \"{key}\" volvió con confianza {sure}, por debajo del mínimo de {floor}."),
"ai.why.unreachable": ("não foi possível falar com o modelo: {error}", "could not reach the model: {error}", "no se pudo contactar con el modelo: {error}"),
"ai.why.unreadable": ("o modelo devolveu algo ilegível", "the model returned something unreadable", "el modelo devolvió algo ilegible"),
"ai.why.refused": ("{error}", "{error}", "{error}"),
"ai.why.other-model": ("a resposta veio de \"{answered}\", que não é o \"{model}\" indicado em judge.model.", "the answer came back from \"{answered}\", which is not the \"{model}\" named in judge.model.", "la respuesta vino de \"{answered}\", que no es el \"{model}\" indicado en judge.model."),
"ai.why.no-answers": ("o modelo não respondeu nada.", "the model answered nothing.", "el modelo no respondió nada."),
"err.notFound": ("{path} não existe (foi movido ou apagado?).", "{path} does not exist (was it moved or deleted?).", "{path} no existe (¿se movió o se borró?)."),
"err.denied": ("Sem permissão para acessar {path}.", "No permission to access {path}.", "Sin permiso para acceder a {path}."),
"err.isDir": ("{path} é uma pasta, não um arquivo.", "{path} is a folder, not a file.", "{path} es una carpeta, no un archivo."),
"err.diskFull": ("Não há espaço livre no disco para gravar {path}.", "There is no free disk space to write {path}.", "No hay espacio libre en el disco para escribir {path}."),
"err.readOnly": ("{path} está num disco somente leitura.", "{path} is on a read-only disk.", "{path} está en un disco de solo lectura."),
"err.nameTooLong": ("O nome do arquivo é longo demais: {path}", "The file name is too long: {path}", "El nombre del archivo es demasiado largo: {path}"),
"err.io": ("Erro ao acessar {path} ({detail}).", "Error accessing {path} ({detail}).", "Error al acceder a {path} ({detail})."),
"err.notText": ("{path} não é um arquivo de texto UTF-8.", "{path} is not a UTF-8 text file.", "{path} no es un archivo de texto UTF-8."),
"err.noKey": ("Nenhuma chave da OpenRouter guardada. Adicione-a em Preferências.", "No OpenRouter key saved. Add it in Preferences.", "No hay ninguna clave de OpenRouter guardada. Agréguela en Preferencias."),
"err.notOpenRouter": ("Recusado: {url} não é um endereço da OpenRouter.", "Refused: {url} is not an OpenRouter address.", "Rechazado: {url} no es una dirección de OpenRouter."),
"err.unreadable": ("resposta ilegível", "unreadable answer", "respuesta ilegible"),
"err.http": ("o pedido falhou (HTTP {status})", "the request failed (HTTP {status})", "la solicitud falló (HTTP {status})"),
"err.emptyKey": ("A chave está vazia.", "The key is empty.", "La clave está vacía."),
# preview
"preview.title": ("Preview do curso", "Course preview", "Vista previa del curso"),
"preview.restart": ("Recomeçar", "Start over", "Reiniciar"),
"preview.lang": ("Idioma", "Language", "Idioma"),
"preview.langAuto": ("automático", "automatic", "automático"),
"preview.reload": ("Aplicar alterações", "Apply changes", "Aplicar cambios"),
"preview.reloadHint": ("O curso mudou: recarrega o preview com a versão nova, mantendo o estudante onde está", "The course changed: reloads the preview with the new version, keeping the student where they are", "El curso cambió: recarga la vista previa con la versión nueva, manteniendo al estudiante donde está"),
"preview.noKey": ("Sem chave da OpenRouter: modo degradado (geração indisponível, julgamentos manuais).", "No OpenRouter key: degraded mode (no generation, manual judgements).", "Sin clave de OpenRouter: modo degradado (sin generación, juicios manuales)."),
"preview.configure": ("Configurar", "Configure", "Configurar"),
"preview.forcedMode": ("Julgamento forçado ativo", "Forced judgement active", "Juicio forzado activo"),
"preview.forced": ("forçado", "forced", "forzado"),
"preview.calls": ("Chamadas", "Calls", "Llamadas"),
"preview.state": ("Estado", "State", "Estado"),
"preview.path": ("Caminho", "Path", "Camino"),
"preview.judges": ("Forçar julgamento", "Force judgement", "Forzar juicio"),
"preview.callCount": ("{n} chamadas", "{n} calls", "{n} llamadas"),
"preview.clear": ("limpar", "clear", "limpiar"),
"preview.notJudged": ("não julgado", "not judged", "no juzgado"),
"preview.node": ("Nó", "Node", "Nodo"),
"preview.endpoint": ("Endpoint", "Endpoint", "Endpoint"),
"preview.model": ("Modelo", "Model", "Modelo"),
"preview.sent": ("Corpo enviado", "Body sent", "Cuerpo enviado"),
"preview.raw": ("Resposta crua", "Raw answer", "Respuesta cruda"),
"preview.notStarted": ("O estudante ainda não começou.", "The student has not started yet.", "El estudiante aún no ha empezado."),
"preview.current": ("Passo atual", "Current step", "Paso actual"),
"preview.finished": ("fim do curso", "end of course", "fin del curso"),
"preview.showing": ("Exibindo", "Showing", "Mostrando"),
"preview.showInGraph": ("mostrar no grafo", "show on the graph", "mostrar en el grafo"),
"preview.key": ("Chave", "Key", "Clave"),
"preview.value": ("Valor", "Value", "Valor"),
"preview.scale": ("Escala", "Scale", "Escala"),
"preview.spread": ("peso por nível (do player)", "weight per level (the player's)", "peso por nivel (del player)"),
"preview.pathHint": ("Cada passo, a edge tomada e a condição que a decidiu. O caminho também aparece no grafo.", "Each step, the edge taken and the condition that decided it. The path also shows on the graph.", "Cada paso, la arista tomada y la condición que la decidió. El camino también aparece en el grafo."),
"preview.end": ("fim", "end", "fin"),
"preview.backTo": ("Voltar ao nó", "Back to node", "Volver al nodo"),
"preview.noJudges": ("O curso não tem nós de julgamento.", "The course has no judgement nodes.", "El curso no tiene nodos de juicio."),
"preview.forceHint": ("Substitui a resposta da IA por um valor seu, para testar um ramo. Vale só para esta sessão e nunca é salvo.", "Replaces the AI's answer with a value of yours, to test a branch. Only for this session; never saved.", "Sustituye la respuesta de la IA por un valor suyo, para probar una rama. Solo para esta sesión; nunca se guarda."),
"preview.confidence": ("confiança", "confidence", "confianza"),
# probe
"probe.open": ("Testar julgamento", "Test judgement", "Probar juicio"),
"probe.title": ("Testar julgamento", "Test judgement", "Probar juicio"),
"probe.sample": ("Valores de exemplo", "Sample values", "Valores de ejemplo"),
"probe.noKeys": ("O state não lê nenhuma chave {{STORAGE}}.", "The state reads no {{STORAGE}} key.", "El state no lee ninguna clave {{STORAGE}}."),
"probe.unknownKey": ("chave desconhecida", "unknown key", "clave desconocida"),
"probe.body": ("Corpo que será enviado a /api/alpha/decisions", "Body sent to /api/alpha/decisions", "Cuerpo enviado a /api/alpha/decisions"),
"probe.send": ("Enviar à IA", "Send to the AI", "Enviar a la IA"),
"probe.needKey": ("É preciso uma chave da OpenRouter.", "An OpenRouter key is needed.", "Se necesita una clave de OpenRouter."),
"probe.settings": ("{model} · piso {floor} · slug estrito {strict}", "{model} · floor {floor} · strict slug {strict}", "{model} · mínimo {floor} · slug estricto {strict}"),
"probe.raw": ("Resposta crua", "Raw answer", "Respuesta cruda"),
"probe.paste": ("Colar uma resposta (sem chamar a IA)", "Paste an answer (without calling the AI)", "Pegar una respuesta (sin llamar a la IA)"),
"probe.tryPasted": ("Avaliar resposta colada", "Evaluate pasted answer", "Evaluar respuesta pegada"),
"probe.result": ("Chaves que seriam gravadas", "Keys that would be stored", "Claves que se guardarían"),
"probe.judged": ("Julgado: as chaves abaixo seriam gravadas.", "Judged: the keys below would be stored.", "Juzgado: se guardarían las claves de abajo."),
"probe.notJudged": ("Não julgado — nada é gravado e o estudante sai pela fallback", "Not judged — nothing is stored and the student leaves by the fallback", "No juzgado — no se guarda nada y el estudiante sale por el fallback"),
"probe.edge": ("Edge que o estudante tomaria", "Edge the student would take", "Arista que tomaría el estudiante"),
"probe.noEdge": ("nenhuma: o curso terminaria aqui", "none: the course would end here", "ninguna: el curso terminaría aquí"),
# prefs
"prefs.title": ("Preferências", "Preferences", "Preferencias"),
"prefs.defaults": ("Restaurar padrões", "Restore defaults", "Restaurar valores predeterminados"),
"prefs.key": ("Chave da OpenRouter", "OpenRouter key", "Clave de OpenRouter"),
"prefs.keyHint": ("Guardada no Keychain do macOS e usada só pelo lado nativo do app; a interface nunca a vê.", "Kept in the macOS Keychain and used only by the app's native side; the interface never sees it.", "Guardada en el llavero de macOS y usada solo por la parte nativa de la app; la interfaz nunca la ve."),
"prefs.keySet": ("configurada", "configured", "configurada"),
"prefs.keyMissing": ("não configurada", "not configured", "no configurada"),
"prefs.keySave": ("Guardar chave", "Store key", "Guardar clave"),
"prefs.keySaved": ("Chave guardada no Keychain.", "Key stored in the Keychain.", "Clave guardada en el llavero."),
"prefs.keyDelete": ("Apagar", "Delete", "Borrar"),
"prefs.keyDeleted": ("Chave apagada.", "Key deleted.", "Clave borrada."),
"prefs.generation": ("Geração (dynamic-md, dynamic-html)", "Generation (dynamic-md, dynamic-html)", "Generación (dynamic-md, dynamic-html)"),
"prefs.model": ("Modelo", "Model", "Modelo"),
"prefs.temperature": ("Temperatura", "Temperature", "Temperatura"),
"prefs.maxTokens": ("Limite de tokens", "Token limit", "Límite de tokens"),
"prefs.judge": ("Julgamento (choice, score, noul)", "Judgement (choice, score, noul)", "Juicio (choice, score, noul)"),
"prefs.judgeHint": ("Os mesmos valores do config.php do player, para que o que for calibrado aqui valha em produção.", "The same values as the player's config.php, so what is calibrated here holds in production.", "Los mismos valores que el config.php del player, para que lo calibrado aquí valga en producción."),
"prefs.judgeModel": ("Modelo (slug exato)", "Model (exact slug)", "Modelo (slug exacto)"),
"prefs.minConfidence": ("Piso de confiança", "Confidence floor", "Confianza mínima"),
"prefs.strictModel": ("Slug estrito", "Strict slug", "Slug estricto"),
"prefs.strictHint": ("recusar resposta de outro modelo (aceita sufixo de data)", "refuse an answer from another model (date suffix allowed)", "rechazar respuestas de otro modelo (se admite sufijo de fecha)"),
"prefs.judgeUrl": ("Endpoint de decisões", "Decisions endpoint", "Endpoint de decisiones"),
"prefs.app": ("Aplicativo", "Application", "Aplicación"),
"prefs.uiLang": ("Idioma da interface", "Interface language", "Idioma de la interfaz"),
"prefs.theme": ("Tema", "Theme", "Tema"),
"prefs.themeSystem": ("Do sistema", "System", "Del sistema"),
"prefs.themeLight": ("Claro", "Light", "Claro"),
"prefs.themeDark": ("Escuro", "Dark", "Oscuro"),
"prefs.agent": ("Agente de IA", "AI agent", "Agente de IA"),
"prefs.agentHint": ("O agente segue estas instruções em toda sessão, como um CLAUDE.md: o público, o tom, o jeito de montar os cursos. Valem a partir da próxima sessão.", "The agent follows these instructions in every session, like a CLAUDE.md: the audience, the tone, how to build courses. They apply from the next session on.", "El agente sigue estas instrucciones en cada sesión, como un CLAUDE.md: el público, el tono, la forma de armar los cursos. Valen a partir de la próxima sesión."),
"prefs.agentInstructions": ("Instruções para o agente", "Instructions for the agent", "Instrucciones para el agente"),
"prefs.agentPlaceholder": ("Ex.: Meus alunos são do 1º ano do ensino médio. Use tom informal. Termine cada seção com um quiz de 3 perguntas.", "E.g.: My students are in 10th grade. Use an informal tone. End each section with a 3-question quiz.", "Ej.: Mis estudiantes son de 1.º de bachillerato. Use un tono informal. Termine cada sección con un cuestionario de 3 preguntas."),
"prefs.agentMcp": ("Servidores MCP", "MCP servers", "Servidores MCP"),
"prefs.agentMcpHint": ("O JSON de um .mcp.json do Claude Code, como a documentação de cada servidor mostra. O comando precisa estar no PATH ou ter o caminho inteiro. Servidores que pedem login (OAuth) não funcionam aqui: use headers ou env. Fica num arquivo comum, fora do Keychain. Vale a partir da próxima sessão.", "The JSON of a Claude Code .mcp.json, as each server's documentation shows it. The command must be on the PATH or have its full path. Servers that need a login (OAuth) don't work here: use headers or env. It is kept in a plain file, not in the Keychain. It applies from the next session on.", "El JSON de un .mcp.json de Claude Code, como lo muestra la documentación de cada servidor. El comando debe estar en el PATH o tener la ruta completa. Los servidores que piden inicio de sesión (OAuth) no funcionan aquí: use headers o env. Se guarda en un archivo común, fuera del Llavero. Vale a partir de la próxima sesión."),
"prefs.agentSkills": ("Skills", "Skills", "Skills"),
"prefs.agentSkillsHint": ("Para instalar uma skill, ponha a pasta dela (com o SKILL.md) na pasta das skills. Valem a partir da próxima sessão. Comandos que uma skill rode sempre pedem aprovação.", "To install a skill, put its folder (with its SKILL.md) in the skills folder. They apply from the next session on. Commands a skill runs always ask for approval.", "Para instalar una skill, ponga su carpeta (con el SKILL.md) en la carpeta de skills. Valen a partir de la próxima sesión. Los comandos que ejecute una skill siempre piden aprobación."),
"prefs.skillsLoading": ("Procurando as skills…", "Looking for skills…", "Buscando las skills…"),
"prefs.skillsNone": ("Nenhuma skill instalada.", "No skills installed.", "Ninguna skill instalada."),
"prefs.skillsUnavailable": ("As skills só aparecem com o agente disponível (no app, com o Node instalado).", "Skills only show with the agent available (in the app, with Node installed).", "Las skills solo aparecen con el agente disponible (en la app, con Node instalado)."),
"prefs.skillsReveal": ("Abrir pasta das skills", "Open skills folder", "Abrir carpeta de skills"),
"prefs.skillsReload": ("Recarregar", "Reload", "Recargar"),
"mcp.notJson": ("Não é um JSON válido: {detail}", "Not valid JSON: {detail}", "No es un JSON válido: {detail}"),
"mcp.notServers": ("Esperava um objeto com os servidores, ou {\"mcpServers\": {…}}.", "Expected an object of servers, or {\"mcpServers\": {…}}.", "Se esperaba un objeto con los servidores, o {\"mcpServers\": {…}}."),
"mcp.notObject": ("O servidor \"{name}\" precisa ser um objeto.", "Server \"{name}\" must be an object.", "El servidor \"{name}\" debe ser un objeto."),
"mcp.noCommand": ("O servidor \"{name}\" não tem \"command\".", "Server \"{name}\" has no \"command\".", "El servidor \"{name}\" no tiene \"command\"."),
"mcp.noUrl": ("O servidor \"{name}\" precisa de uma \"url\" http(s).", "Server \"{name}\" needs an http(s) \"url\".", "El servidor \"{name}\" necesita una \"url\" http(s)."),
"mcp.badField": ("No servidor \"{name}\", \"{field}\" está no formato errado.", "In server \"{name}\", \"{field}\" has the wrong format.", "En el servidor \"{name}\", \"{field}\" tiene el formato incorrecto."),
"mcp.badType": ("O servidor \"{name}\" tem o tipo \"{type}\": use stdio, http ou sse.", "Server \"{name}\" has type \"{type}\": use stdio, http or sse.", "El servidor \"{name}\" tiene el tipo \"{type}\": use stdio, http o sse."),
"mcp.reserved": ("O nome \"{name}\" é do próprio editor: escolha outro.", "The name \"{name}\" belongs to the editor: pick another.", "El nombre \"{name}\" es del propio editor: elija otro."),
# AI agent (side panel)
"agent.title": ("Agente de IA", "AI agent", "Agente de IA"),
"agent.newSession": ("Nova sessão", "New session", "Nueva sesión"),
"agent.sessions": ("Sessões", "Sessions", "Sesiones"),
"agent.close": ("Fechar o painel", "Close the panel", "Cerrar el panel"),
"sidebar.toggle": ("Mostrar/ocultar a barra lateral", "Show/hide the sidebar", "Mostrar/ocultar la barra lateral"),
"agent.untitled": ("Nova sessão", "New session", "Nueva sesión"),
"agent.searchSessions": ("Buscar sessões", "Search sessions", "Buscar sesiones"),
"agent.noSessions": ("Nenhuma sessão ainda.", "No sessions yet.", "Aún no hay sesiones."),
"agent.noMatch": ("Nenhuma sessão encontrada.", "No session found.", "No se encontró ninguna sesión."),
"agent.deleteSession": ("Excluir sessão", "Delete session", "Eliminar sesión"),
"agent.deleteConfirm": ("Excluir a sessão “{name}”? Ela não poderá ser recuperada.", "Delete the session “{name}”? It cannot be recovered.", "¿Eliminar la sesión “{name}”? No se podrá recuperar."),
"agent.today": ("Hoje", "Today", "Hoy"),
"agent.yesterday": ("Ontem", "Yesterday", "Ayer"),
"agent.week": ("Últimos 7 dias", "Last 7 days", "Últimos 7 días"),
"agent.older": ("Mais antigas", "Older", "Anteriores"),
"agent.hello": ("Como posso ajudar com o curso?", "How can I help with the course?", "¿Cómo puedo ayudar con el curso?"),
"agent.lead": ("Peça para criar passos, revisar e traduzir textos, montar uma tarefa avaliada pela IA ou corrigir os problemas do curso. Cada alteração do agente pode ser desfeita com ⌘Z.", "Ask it to create steps, review and translate texts, build a task the AI evaluates or fix the course's problems. Each change the agent makes can be undone with ⌘Z.", "Pídale crear pasos, revisar y traducir textos, armar una tarea evaluada por la IA o corregir los problemas del curso. Cada cambio del agente se puede deshacer con ⌘Z."),
"agent.try1": ("Revise o curso e corrija os erros de validação", "Review the course and fix the validation errors", "Revisa el curso y corrige los errores de validación"),
"agent.try2": ("Crie um quiz de 3 perguntas sobre o passo selecionado", "Create a 3-question quiz about the selected step", "Crea un cuestionario de 3 preguntas sobre el paso seleccionado"),
"agent.try3": ("Traduza os textos que faltam em todos os idiomas do curso", "Translate the missing texts into every language of the course", "Traduce los textos que faltan a todos los idiomas del curso"),
"agent.try4": ("Crie um curso curto sobre frações para o 6º ano", "Create a short course on fractions for 6th grade", "Crea un curso corto sobre fracciones para 6º grado"),
"agent.account": ("Conta do Claude: {email}", "Claude account: {email}", "Cuenta de Claude: {email}"),
"agent.connecting": ("Iniciando o agente…", "Starting the agent…", "Iniciando el agente…"),
"agent.retry": ("Tentar de novo", "Try again", "Reintentar"),
"agent.details": ("Detalhes", "Details", "Detalles"),
"agent.err.unavailable": ("O agente funciona dentro do app (npm run app:dev). Num navegador ele não tem como iniciar.", "The agent works inside the app (npm run app:dev). In a browser it cannot start.", "El agente funciona dentro de la app (npm run app:dev). En un navegador no puede iniciarse."),
"agent.err.node-missing": ("O Node.js 18 ou mais novo não foi encontrado neste Mac. Instale-o (nodejs.org) e tente de novo.", "Node.js 18 or newer was not found on this Mac. Install it (nodejs.org) and try again.", "No se encontró Node.js 18 o más reciente en este Mac. Instálelo (nodejs.org) y vuelva a intentarlo."),
"agent.err.sidecar-missing": ("Os arquivos do agente (a pasta agent/ do projeto) não foram encontrados.", "The agent's files (the project's agent/ folder) were not found.", "No se encontraron los archivos del agente (la carpeta agent/ del proyecto)."),
"agent.err.sdk-missing": ("O Claude Agent SDK não está instalado. Rode npm install na pasta do projeto e tente de novo.", "The Claude Agent SDK is not installed. Run npm install in the project folder and try again.", "El Claude Agent SDK no está instalado. Ejecute npm install en la carpeta del proyecto y vuelva a intentarlo."),
"agent.err.exited": ("O processo do agente parou ao iniciar.", "The agent's process stopped while starting.", "El proceso del agente se detuvo al iniciarse."),
"agent.err.timeout": ("O agente não respondeu a tempo.", "The agent did not answer in time.", "El agente no respondió a tiempo."),
"agent.err.failed": ("Não foi possível iniciar o agente.", "The agent could not start.", "No se pudo iniciar el agente."),
"agent.loginTitle": ("Nenhuma conta do Claude conectada", "No Claude account signed in", "Ninguna cuenta de Claude conectada"),
"agent.loginHelp": ("O agente usa a conta do Claude com que o Claude Code está logado neste Mac. No Terminal, rode claude e, nele, /login; depois clique em Tentar de novo.", "The agent uses the Claude account Claude Code is signed in with on this Mac. In Terminal, run claude and, in it, /login; then click Try again.", "El agente usa la cuenta de Claude con la que Claude Code inició sesión en este Mac. En la Terminal, ejecute claude y, dentro, /login; luego haga clic en Reintentar."),
"agent.n.interrupted": ("Interrompido.", "Interrupted.", "Interrumpido."),
"agent.n.authentication_failed": ("A conta do Claude não está autenticada. Faça login no Claude Code (claude → /login) e tente de novo.", "The Claude account is not authenticated. Sign in to Claude Code (claude → /login) and try again.", "La cuenta de Claude no está autenticada. Inicie sesión en Claude Code (claude → /login) y vuelva a intentarlo."),
"agent.n.oauth_org_not_allowed": ("A organização desta conta do Claude não permite este uso.", "This Claude account's organization does not allow this use.", "La organización de esta cuenta de Claude no permite este uso."),
"agent.n.account_on_hold": ("A conta do Claude está suspensa.", "The Claude account is on hold.", "La cuenta de Claude está suspendida."),
"agent.n.billing_error": ("Há um problema de cobrança na conta do Claude.", "There is a billing problem with the Claude account.", "Hay un problema de facturación en la cuenta de Claude."),
"agent.n.rate_limit": ("Limite de uso da conta atingido. Tente mais tarde.", "The account's usage limit was reached. Try again later.", "Se alcanzó el límite de uso de la cuenta. Inténtelo más tarde."),
"agent.n.rate_rejected": ("Limite de uso da conta do Claude atingido{when}.", "The Claude account's usage limit was reached{when}.", "Se alcanzó el límite de uso de la cuenta de Claude{when}."),
"agent.n.rate_warning": ("Perto do limite de uso da conta do Claude{when}.", "Close to the Claude account's usage limit{when}.", "Cerca del límite de uso de la cuenta de Claude{when}."),
"agent.n.resets": (" — renova às {time}", " — resets at {time}", " — se renueva a las {time}"),
"agent.n.overloaded": ("O Claude está sobrecarregado agora. Tente de novo em instantes.", "Claude is overloaded right now. Try again in a moment.", "Claude está sobrecargado ahora. Vuelva a intentarlo en un momento."),
"agent.n.invalid_request": ("O pedido foi recusado pela API.", "The API refused the request.", "La API rechazó la solicitud."),
"agent.n.model_not_found": ("Este modelo não está disponível para a sua conta. Escolha outro.", "This model is not available to your account. Choose another.", "Este modelo no está disponible para su cuenta. Elija otro."),
"agent.n.server_error": ("Erro no servidor do Claude. Tente de novo.", "Claude's server failed. Try again.", "Error en el servidor de Claude. Vuelva a intentarlo."),
"agent.n.max_output_tokens": ("A resposta ficou longa demais e foi cortada.", "The answer got too long and was cut.", "La respuesta fue demasiado larga y se cortó."),
"agent.n.error_max_turns": ("O agente parou: limite de passos da tarefa atingido.", "The agent stopped: the task's step limit was reached.", "El agente se detuvo: se alcanzó el límite de pasos de la tarea."),
"agent.n.error_during_execution": ("O agente parou com um erro.", "The agent stopped with an error.", "El agente se detuvo con un error."),
"agent.n.error_max_budget_usd": ("O agente parou: limite de custo atingido.", "The agent stopped: the cost limit was reached.", "El agente se detuvo: se alcanzó el límite de costo."),
"agent.n.exited": ("O processo do agente parou. A próxima mensagem retoma esta conversa.", "The agent's process stopped. The next message picks this conversation up again.", "El proceso del agente se detuvo. El próximo mensaje retoma esta conversación."),
"agent.n.ended": ("A conversa foi encerrada com um erro. A próxima mensagem a retoma.", "The conversation ended with an error. The next message picks it up again.", "La conversación terminó con un error. El próximo mensaje la retoma."),
"agent.n.send": ("A mensagem não pôde ser enviada.", "The message could not be sent.", "No se pudo enviar el mensaje."),
"agent.compacted": ("Conversa compactada para caber no contexto", "Conversation compacted to fit the context", "Conversación compactada para caber en el contexto"),
"agent.thinking": ("Pensando…", "Thinking…", "Pensando…"),
"agent.thought": ("Raciocínio", "Reasoning", "Razonamiento"),
"agent.tool.get_editor_state": ("Ver o editor", "Look at the editor", "Ver el editor"),
"agent.tool.read_course": ("Ler o curso", "Read the course", "Leer el curso"),
"agent.tool.read_nodes": ("Ler {nodes}", "Read {nodes}", "Leer {nodes}"),
"agent.tool.validate_course": ("Validar o curso", "Validate the course", "Validar el curso"),
"agent.tool.get_schema": ("Consultar o schema", "Look up the schema", "Consultar el schema"),
"agent.tool.edit_course": ("Editar o curso", "Edit the course", "Editar el curso"),
"agent.tool.replace_course": ("Reescrever o curso", "Rewrite the course", "Reescribir el curso"),
"agent.tool.new_course": ("Criar um curso", "Create a course", "Crear un curso"),
"agent.tool.show_node": ("Mostrar {id}", "Show {id}", "Mostrar {id}"),
"agent.tool.auto_layout": ("Organizar o grafo", "Arrange the graph", "Organizar el grafo"),
"agent.tool.Read": ("Ler arquivo", "Read file", "Leer archivo"),
"agent.tool.Glob": ("Procurar arquivos", "Find files", "Buscar archivos"),
"agent.tool.Grep": ("Buscar em arquivos", "Search in files", "Buscar en archivos"),
"agent.tool.WebSearch": ("Pesquisar na web", "Search the web", "Buscar en la web"),
"agent.tool.WebFetch": ("Abrir página", "Open page", "Abrir página"),
"agent.tool.Bash": ("Rodar comando", "Run command", "Ejecutar comando"),
"agent.tool.Skill": ("Usar skill", "Use skill", "Usar skill"),
"agent.tool.TodoWrite": ("Tarefas", "Tasks", "Tareas"),
"agent.tool.AskUserQuestion": ("Pergunta", "Question", "Pregunta"),
"agent.tool.ExitPlanMode": ("Plano", "Plan", "Plan"),
"agent.result": ("Resultado", "Result", "Resultado"),
"agent.input": ("Entrada", "Input", "Entrada"),
"agent.ask.edit": ("Aplicar esta alteração ao curso?", "Apply this change to the course?", "¿Aplicar este cambio al curso?"),
"agent.ask.replace": ("Substituir o curso inteiro?", "Replace the whole course?", "¿Reemplazar todo el curso?"),
"agent.ask.new": ("Criar um curso novo numa aba?", "Create a new course in a tab?", "¿Crear un curso nuevo en una pestaña?"),
"agent.ask.read": ("Ler este arquivo do seu Mac?", "Read this file on your Mac?", "¿Leer este archivo de su Mac?"),
"agent.ask.find": ("Procurar arquivos nesta pasta do seu Mac?", "Search files in this folder on your Mac?", "¿Buscar archivos en esta carpeta de su Mac?"),
"agent.ask.fetch": ("Abrir esta página da web?", "Open this web page?", "¿Abrir esta página web?"),
"agent.ask.websearch": ("Pesquisar na web?", "Search the web?", "¿Buscar en la web?"),
"agent.ask.bash": ("Rodar este comando no Mac?", "Run this command on the Mac?", "¿Ejecutar este comando en el Mac?"),
"agent.skills": ("Skills ({n})", "Skills ({n})", "Skills ({n})"),
"agent.mcp": ("MCP", "MCP", "MCP"),
"agent.mcp.connected": ("Conectado", "Connected", "Conectado"),
"agent.mcp.pending": ("Conectando…", "Connecting…", "Conectando…"),
"agent.mcp.failed": ("Falhou", "Failed", "Falló"),
"agent.mcp.needs-auth": ("Pede login, o que não funciona aqui", "Needs a login, which doesn't work here", "Pide inicio de sesión, lo que no funciona aquí"),
"agent.mcp.disabled": ("Desligado", "Disabled", "Desactivado"),
"agent.ask.other": ("Permitir que o agente use {tool}?", "Allow the agent to use {tool}?", "¿Permitir que el agente use {tool}?"),
"agent.allow": ("Permitir", "Allow", "Permitir"),
"agent.allowAlways": ("Permitir sempre nesta sessão", "Always allow in this session", "Permitir siempre en esta sesión"),
"agent.deny": ("Recusar", "Decline", "Rechazar"),
"agent.denyWith": ("Recusar e dizer o que fazer", "Decline and say what to do", "Rechazar y decir qué hacer"),
"agent.feedbackPlaceholder": ("O que o agente deve fazer em vez disso?", "What should the agent do instead?", "¿Qué debería hacer el agente en su lugar?"),
"agent.op.add": ("Adicionar {id}", "Add {id}", "Añadir {id}"),
"agent.op.update": ("Alterar {id}", "Change {id}", "Cambiar {id}"),
"agent.op.delete": ("Excluir {id}", "Delete {id}", "Eliminar {id}"),
"agent.op.rename": ("Renomear {id} → {to}", "Rename {id} → {to}", "Renombrar {id} → {to}"),
"agent.op.edges": ("Setas que saem de {id}", "Edges leaving {id}", "Flechas que salen de {id}"),
"agent.op.info": ("Informações do curso", "Course info", "Información del curso"),
"agent.op.nodes": ("{n} passos, {e} setas", "{n} steps, {e} edges", "{n} pasos, {e} flechas"),
"agent.q.other": ("Outra resposta…", "Other answer…", "Otra respuesta…"),
"agent.q.submit": ("Responder", "Answer", "Responder"),
"agent.q.skip": ("Pular", "Skip", "Omitir"),
"agent.q.skipped": ("A pessoa preferiu não responder.", "The person chose not to answer.", "La persona prefirió no responder."),
"agent.plan.title": ("Plano do agente", "The agent's plan", "Plan del agente"),
"agent.plan.approveAuto": ("Aprovar e editar automaticamente", "Approve and edit automatically", "Aprobar y editar automáticamente"),
"agent.plan.approveAsk": ("Aprovar e pedir antes de editar", "Approve and ask before editing", "Aprobar y pedir antes de editar"),
"agent.plan.keep": ("Continuar planejando", "Keep planning", "Seguir planificando"),
"agent.plan.seeAbove": ("O plano está na mensagem acima.", "The plan is in the message above.", "El plan está en el mensaje de arriba."),
"agent.plan.ready": ("Executar o plano?", "Carry out the plan?", "¿Ejecutar el plan?"),
"agent.plan.go": ("Plano aprovado: pode executar.", "Plan approved: go ahead.", "Plan aprobado: adelante."),
"agent.plan.keepPlaceholder": ("O que mudar no plano?", "What should change in the plan?", "¿Qué cambiar en el plan?"),
"agent.placeholder": ("Peça ao agente… (↵ envia, ⇧↵ quebra a linha)", "Ask the agent… (↵ sends, ⇧↵ new line)", "Pida al agente… (↵ envía, ⇧↵ salto de línea)"),
"agent.placeholderBusy": ("Escreva para pôr uma mensagem na fila…", "Write to queue a message…", "Escriba para poner un mensaje en cola…"),
"agent.send": ("Enviar (↵)", "Send (↵)", "Enviar (↵)"),
"agent.stop": ("Interromper (Esc)", "Stop (Esc)", "Detener (Esc)"),
"agent.attach": ("Anexar arquivo (o agente pede para lê-lo)", "Attach a file (the agent asks to read it)", "Adjuntar archivo (el agente pide leerlo)"),
"agent.selectionOn": ("A seleção vai junto com a mensagem. Clique para não enviar.", "The selection goes with the message. Click to leave it out.", "La selección va con el mensaje. Haga clic para no enviarla."),
"agent.selectionOff": ("A seleção não vai junto. Clique para enviar.", "The selection is left out. Click to send it.", "La selección no va. Haga clic para enviarla."),
"agent.mode": ("Modo", "Mode", "Modo"),
"agent.mode.ask": ("Pedir antes de editar", "Ask before editing", "Pedir antes de editar"),
"agent.mode.auto": ("Editar automaticamente", "Edit automatically", "Editar automáticamente"),
"agent.mode.plan": ("Planejar", "Plan", "Planificar"),
"agent.modeShort.ask": ("Pedir antes", "Ask first", "Pedir antes"),
"agent.modeShort.auto": ("Automático", "Auto edit", "Automático"),
"agent.modeShort.plan": ("Planejar", "Plan", "Planificar"),
"agent.mode.askHint": ("Cada alteração no curso espera a sua aprovação.", "Each change to the course waits for your approval.", "Cada cambio en el curso espera su aprobación."),
"agent.mode.autoHint": ("O agente altera o curso sem perguntar; tudo pode ser desfeito com ⌘Z.", "The agent changes the course without asking; everything can be undone with ⌘Z.", "El agente cambia el curso sin preguntar; todo se puede deshacer con ⌘Z."),
"agent.mode.planHint": ("O agente estuda o curso e propõe um plano; nada muda até você aprovar.", "The agent studies the course and proposes a plan; nothing changes until you approve.", "El agente estudia el curso y propone un plan; nada cambia hasta que usted lo apruebe."),
"agent.model": ("Modelo", "Model", "Modelo"),
"agent.effort": ("Esforço", "Effort", "Esfuerzo"),
"agent.effortHint": ("Quanto o modelo pensa antes de agir: mais esforço, respostas mais cuidadosas e mais lentas.", "How much the model thinks before acting: more effort, more careful and slower answers.", "Cuánto piensa el modelo antes de actuar: más esfuerzo, respuestas más cuidadosas y lentas."),
"agent.effort.auto": ("Padrão", "Default", "Predeterminado"),
"agent.effort.low": ("Baixo", "Low", "Bajo"),
"agent.effort.medium": ("Médio", "Medium", "Medio"),
"agent.effort.high": ("Alto", "High", "Alto"),
"agent.effort.xhigh": ("Muito alto", "Extra high", "Muy alto"),
"agent.effort.max": ("Máximo", "Max", "Máximo"),
"agent.signedIn": ("Conectado como {email}", "Signed in as {email}", "Conectado como {email}"),
"agent.usage": ("Uso da conta", "Account usage", "Uso de la cuenta"),
"agent.usageRefresh": ("Atualizar o uso", "Refresh the usage", "Actualizar el uso"),
"agent.usageUpdated": ("Do /usage do Claude Code, às {time}", "From Claude Code's /usage, at {time}", "Del /usage de Claude Code, a las {time}"),
"agent.usageLoading": ("Consultando o uso…", "Checking the usage…", "Consultando el uso…"),
"agent.usageFailed": ("Não foi possível consultar o uso.", "The usage could not be checked.", "No se pudo consultar el uso."),
# help
"help.title": ("Guia rápido", "Quick guide", "Guía rápida"),
"help.lead": ("Um curso é um grafo: os nós são o que o estudante vê e faz, as edges dizem o que vem depois.", "A course is a graph: the nodes are what the student sees and does, the edges say what comes next.", "Un curso es un grafo: los nodos son lo que el estudiante ve y hace, las aristas dicen qué viene después."),
"help.step1": ("Insira nós pelo botão + da barra ou pelo menu Inserir; para escolher onde um nó fica, arraste o tipo da lista do + até o grafo.", "Insert nodes with the + button on the toolbar or the Insert menu; to choose where one goes, drag its type from the + list onto the graph.", "Inserte nodos con el botón + de la barra o el menú Insertar; para elegir dónde queda uno, arrastre su tipo desde la lista del + al grafo."),
"help.step2": ("Ligue os nós puxando do círculo à direita de um nó até outro.", "Connect nodes by dragging from the circle on a node's right to another node.", "Conecte nodos arrastrando desde el círculo derecho de un nodo hasta otro."),
"help.step3": ("Clique num nó para editar o conteúdo no inspetor; clique numa edge para editar a condição.", "Click a node to edit its content in the inspector; click an edge to edit its condition.", "Haga clic en un nodo para editar su contenido en el inspector; en una arista para editar su condición."),
"help.step4": ("O selo no topo mostra erros e avisos; clique para ver a lista e ir até cada um.", "The badge at the top shows errors and warnings; click it to see the list and jump to each one.", "La insignia arriba muestra errores y avisos; haga clic para ver la lista e ir a cada uno."),
"help.step5": ("Na aba Preview, faça o curso como o estudante, com a IA de verdade.", "In the Preview tab, take the course as the student would, with the real AI.", "En la pestaña Vista previa, haga el curso como el estudiante, con la IA real."),
"help.step6": ("Abra vários cursos ao mesmo tempo, cada um na sua aba, logo abaixo da barra: nós copiados num curso (⌘C) colam em outro (⌘V).", "Open several courses at once, each in its own tab just below the toolbar: nodes copied in one course (⌘C) paste into another (⌘V).", "Abra varios cursos a la vez, cada uno en su pestaña, justo debajo de la barra: los nodos copiados en un curso (⌘C) se pegan en otro (⌘V)."),
"help.step7": ("Clique no ícone ✦ na ponta direita da barra (⇧⌘A) para pedir ao agente de IA que crie, revise, traduza ou corrija passos; cada alteração dele pode ser desfeita com ⌘Z.", "Click the ✦ icon at the right end of the toolbar (⇧⌘A) to ask the AI agent to create, review, translate or fix steps; each change it makes can be undone with ⌘Z.", "Haga clic en el icono ✦ en el extremo derecho de la barra (⇧⌘A) para pedir al agente de IA que cree, revise, traduzca o corrija pasos; cada cambio suyo se puede deshacer con ⌘Z."),
"help.shortcuts": ("Atalhos", "Shortcuts", "Atajos"),
"help.undoRedo": ("Desfazer / refazer", "Undo / redo", "Deshacer / rehacer"),
"help.delete": ("Excluir seleção", "Delete selection", "Eliminar selección"),
"help.copyPaste": ("Copiar / colar nós (também de um curso para outro)", "Copy / paste nodes (from one course to another, too)", "Copiar / pegar nodos (también de un curso a otro)"),
"help.cycleTabs": ("Próxima aba / aba anterior", "Next / previous tab", "Pestaña siguiente / anterior"),
"help.goToTab": ("Ir para a aba 1 … 9 (⌘9: a última)", "Go to tab 1 … 9 (⌘9: the last one)", "Ir a la pestaña 1 … 9 (⌘9: la última)"),
"help.selectAll": ("Selecionar todos os nós", "Select all nodes", "Seleccionar todos los nodos"),
"help.deselect": ("Limpar seleção", "Clear selection", "Limpiar selección"),
"help.docs": ("Guia completo para professores: docs/guia-do-professor.md.", "Full guide for teachers: docs/guia-do-professor.md.", "Guía completa para docentes: docs/guia-do-professor.md."),
}
